apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplepod
spec:
  selector:
    matchLabels:
      app: simplepod
  template:
    metadata:
      labels:
        app: simplepod
    spec:
      containers:
        - name: simplepod
          image: {{ .Values.simplepod.image }}
          command:
            - /bin/sh
            - -c
            - echo "Sleeping {{ .Values.simplepod.sleep }}";sleep {{ .Values.simplepod.sleep }};touch /tmp/hello.txt;echo "THE END. Sleep forever"; sleep 99999998
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe: # Simple liveness/readiness probe to emulate a real application starting
            exec:
              command:
              - ls
              - /tmp/hello.txt
            initialDelaySeconds: {{ .Values.simplepod.sleep }}
            timeoutSeconds: 3
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
              - ls
              - /tmp/hello.txt
            initialDelaySeconds: {{ .Values.simplepod.sleep }}
            timeoutSeconds: 3
            periodSeconds: 20
